name: My Workflow

on:
  workflow_dispatch:
    inputs:
      my-version:
        description: 'Version to use'
        required: true
        default: 'latest'
  pull_request:

# If inputs are present, use the default from there
# Otherwise, default to v3.2.1
env:
  VERSION: ${{ inputs != '' && inputs.my-version || 'v3.2.1' }}

jobs:
  print-version:
    runs-on: ubuntu-latest
    steps:
      - name: Print version
        run: echo ${{ env.VERSION }}
